# Generated by Django 4.2.29 on 2026-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('total_contracts', models.IntegerField(default=0, verbose_name='合同总数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='合同总金额')),
                ('active_contracts', models.IntegerField(default=0, verbose_name='生效合同数')),
                ('completed_contracts', models.IntegerField(default=0, verbose_name='已完成合同数')),
                ('new_contracts', models.IntegerField(default=0, verbose_name='新增合同数')),
                ('new_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='新增合同金额')),
                ('region_data', models.JSONField(blank=True, default=dict, verbose_name='区域分布')),
                ('product_data', models.JSONField(blank=True, default=dict, verbose_name='产品分布')),
            ],
            options={
                'verbose_name': '分析快照',
                'verbose_name_plural': '分析快照',
                'db_table': 'analytics_snapshot',
                'ordering': ['-date'],
            },
        ),
    ]
