# Generated by Django 4.2.29 on 2026-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('action', models.CharField(max_length=20, verbose_name='操作类型')),
                ('target', models.CharField(blank=True, default='', max_length=200, verbose_name='操作对象')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('method', models.CharField(blank=True, default='', max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(blank=True, default='', max_length=500, verbose_name='请求路径')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'sys_operation_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
