# Generated by Django 4.2.29 on 2026-04-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='系统名称')),
                ('system_type', models.CharField(max_length=50, verbose_name='系统类型')),
                ('api_url', models.URLField(max_length=500, verbose_name='接口地址')),
                ('auth_type', models.CharField(default='bearer', max_length=50, verbose_name='认证方式')),
                ('auth_config', models.JSONField(blank=True, default=dict, verbose_name='认证配置')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='字段映射')),
                ('sync_interval', models.IntegerField(default=60, verbose_name='同步间隔(分钟)')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='inactive', max_length=20, verbose_name='状态')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '第三方集成配置',
                'verbose_name_plural': '第三方集成配置',
                'db_table': 'sys_integration_config',
                'ordering': ['-created_at'],
            },
        ),
    ]
