# Generated by Django 4.2.29 on 2026-04-14 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_approvalprocess_contract_approval_status_and_more'),
        ('system', '0003_integrationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('payment_due', '付款到期'), ('delivery_due', '交付到期'), ('contract_expiry', '合同到期'), ('invoice_due', '发票开具'), ('target_progress', '目标达成')], max_length=30, verbose_name='规则类型')),
                ('remind_days', models.PositiveIntegerField(default=7, verbose_name='提前提醒天数')),
                ('owner_role', models.CharField(blank=True, default='', max_length=20, verbose_name='推送角色')),
                ('level', models.CharField(blank=True, default='medium', max_length=20, verbose_name='预警等级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警规则',
                'verbose_name_plural': '预警规则',
                'db_table': 'sys_alert_rule',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10, verbose_name='币种')),
                ('base_currency', models.CharField(default='CNY', max_length=10, verbose_name='本位币')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='汇率')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('is_latest', models.BooleanField(default=True, verbose_name='是否最新汇率')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '汇率配置',
                'verbose_name_plural': '汇率配置',
                'db_table': 'sys_currency_rate',
                'ordering': ['-effective_date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('import', '导入模板'), ('export', '导出模板'), ('report', '报表模板')], max_length=20, verbose_name='模板类型')),
                ('version', models.CharField(default='v1.0', max_length=20, verbose_name='版本号')),
                ('field_config', models.JSONField(blank=True, default=list, verbose_name='字段配置')),
                ('validation_rules', models.JSONField(blank=True, default=list, verbose_name='校验规则')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据模板',
                'verbose_name_plural': '数据模板',
                'db_table': 'sys_data_template',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='目标名称')),
                ('target_type', models.CharField(choices=[('salesperson', '业务员'), ('team', '销售团队'), ('department', '销售部门'), ('region', '区域')], max_length=20, verbose_name='目标维度')),
                ('owner_value', models.CharField(max_length=100, verbose_name='目标对象')),
                ('period_type', models.CharField(choices=[('year', '年度'), ('quarter', '季度'), ('month', '月度')], default='month', max_length=20, verbose_name='周期类型')),
                ('period_label', models.CharField(max_length=30, verbose_name='周期标识')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='目标金额')),
                ('warning_threshold', models.DecimalField(decimal_places=2, default=70, max_digits=5, verbose_name='预警阈值(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '销售目标',
                'verbose_name_plural': '销售目标',
                'db_table': 'sys_sales_target',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StampTaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=50, verbose_name='合同类型')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='税率')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '印花税规则',
                'verbose_name_plural': '印花税规则',
                'db_table': 'sys_stamp_tax_rule',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='operationlog',
            name='after_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='操作后数据'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='before_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='操作前数据'),
        ),
        migrations.CreateModel(
            name='DataPermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('all', '全部数据'), ('self', '本人数据'), ('department', '部门数据'), ('region', '区域数据'), ('customer', '客户数据')], default='self', max_length=20, verbose_name='权限范围')),
                ('scope_value', models.CharField(blank=True, default='', max_length=100, verbose_name='范围值')),
                ('can_edit', models.BooleanField(default=False, verbose_name='是否可编辑')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_permission_rules', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '数据权限规则',
                'verbose_name_plural': '数据权限规则',
                'db_table': 'sys_data_permission_rule',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='驾驶舱名称')),
                ('role_scope', models.CharField(blank=True, default='', max_length=50, verbose_name='适用角色')),
                ('layout', models.JSONField(blank=True, default=list, verbose_name='布局配置')),
                ('widgets', models.JSONField(blank=True, default=list, verbose_name='组件配置')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='移动端模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '驾驶舱配置',
                'verbose_name_plural': '驾驶舱配置',
                'db_table': 'sys_dashboard_config',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('warning_type', models.CharField(max_length=30, verbose_name='预警类型')),
                ('level', models.CharField(default='medium', max_length=20, verbose_name='预警等级')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processed', '已处理')], default='pending', max_length=20, verbose_name='状态')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_messages', to='contracts.contract', verbose_name='合同')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_messages', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_alert_messages', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='system.alertrule', verbose_name='预警规则')),
            ],
            options={
                'verbose_name': '预警消息',
                'verbose_name_plural': '预警消息',
                'db_table': 'sys_alert_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
