# Generated by Django 4.2.29 on 2026-04-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alertrule_currencyrate_datatemplate_salestarget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='category',
            field=models.CharField(choices=[('operation', '操作日志'), ('error', '错误日志'), ('system', '系统日志'), ('security', '安全日志')], default='operation', max_length=20, verbose_name='日志分类'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='耗时(ms)'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='level',
            field=models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], default='info', max_length=20, verbose_name='日志级别'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='module',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='功能模块'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='操作类型'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['-created_at'], name='idx_oplog_created'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['category', '-created_at'], name='idx_oplog_cat'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['level', '-created_at'], name='idx_oplog_level'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['action', '-created_at'], name='idx_oplog_action'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['user', '-created_at'], name='idx_oplog_user'),
        ),
    ]
