# Generated by Django 4.2.29 on 2026-04-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_add_log_category_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='category',
            field=models.CharField(choices=[('operation', '操作日志'), ('error', '错误日志'), ('system', '系统日志'), ('security', '安全日志'), ('contract', '合同日志')], default='operation', max_length=20, verbose_name='日志分类'),
        ),
    ]
