# Generated by Django 4.2.29 on 2026-04-16 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_add_contract_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='客户编码')),
                ('short_name', models.CharField(blank=True, default='', max_length=100, verbose_name='客户简称')),
                ('level', models.CharField(choices=[('vip', 'VIP客户'), ('normal', '普通客户'), ('potential', '潜在客户')], default='normal', max_length=20, verbose_name='客户等级')),
                ('contact_person', models.CharField(blank=True, default='', max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('contact_email', models.CharField(blank=True, default='', max_length=100, verbose_name='联系邮箱')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='地址')),
                ('region', models.CharField(blank=True, default='', max_length=50, verbose_name='区域')),
                ('industry', models.CharField(blank=True, default='', max_length=50, verbose_name='行业')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'biz_customer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='产品类型名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='产品类型编码')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='产品分类')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '产品类型',
                'verbose_name_plural': '产品类型',
                'db_table': 'biz_product_type',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='部门编码')),
                ('manager', models.CharField(blank=True, default='', max_length=50, verbose_name='部门负责人')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='system.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'biz_department',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
