# Generated by Django 4.2.29 on 2026-04-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_no', models.CharField(max_length=50, unique=True, verbose_name='合同编号')),
                ('title', models.CharField(max_length=200, verbose_name='合同标题')),
                ('client_name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('client_contact', models.CharField(blank=True, default='', max_length=50, verbose_name='客户联系人')),
                ('product_type', models.CharField(blank=True, default='', max_length=50, verbose_name='产品类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='合同金额')),
                ('currency', models.CharField(choices=[('CNY', '人民币'), ('USD', '美元'), ('EUR', '欧元')], default='CNY', max_length=10, verbose_name='货币')),
                ('region', models.CharField(blank=True, default='', max_length=50, verbose_name='区域')),
                ('sign_date', models.DateField(blank=True, null=True, verbose_name='签订日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效'), ('completed', '已完成'), ('terminated', '已终止'), ('voided', '已作废')], default='draft', max_length=20, verbose_name='合同状态')),
                ('payment_status', models.CharField(choices=[('unpaid', '未付款'), ('partial', '部分付款'), ('paid', '已付清')], default='unpaid', max_length=20, verbose_name='付款状态')),
                ('delivery_status', models.CharField(choices=[('pending', '待交付'), ('in_progress', '交付中'), ('delivered', '已交付')], default='pending', max_length=20, verbose_name='交付状态')),
                ('salesperson', models.CharField(blank=True, default='', max_length=50, verbose_name='销售人员')),
                ('department', models.CharField(blank=True, default='', max_length=50, verbose_name='部门')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'db_table': 'biz_contract',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=50, verbose_name='变更字段')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='原值')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='新值')),
            ],
            options={
                'verbose_name': '合同变更记录',
                'verbose_name_plural': '合同变更记录',
                'db_table': 'biz_contract_change_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(max_length=50, verbose_name='付款阶段')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='付款金额')),
                ('due_date', models.DateField(verbose_name='应付日期')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='实付日期')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('overdue', '逾期')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='contracts.contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '付款计划',
                'verbose_name_plural': '付款计划',
                'db_table': 'biz_payment_plan',
                'ordering': ['due_date'],
            },
        ),
    ]
