# Generated by Django 4.2.29 on 2026-04-14 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('action_type', models.CharField(choices=[('create', '新增审批'), ('update', '修改审批'), ('delete', '删除审批'), ('change', '变更审批')], max_length=20, verbose_name='操作类型')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='触发金额下限')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='审批步骤')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_processes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '审批流程',
                'verbose_name_plural': '审批流程',
                'db_table': 'biz_approval_process',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='approval_status',
            field=models.CharField(choices=[('not_required', '无需审批'), ('pending', '待审批'), ('approved', '已审批'), ('rejected', '已驳回')], default='not_required', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='contract',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='本位币金额'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='合同类型'),
        ),
        migrations.AddField(
            model_name='contract',
            name='quality_issues',
            field=models.JSONField(blank=True, default=list, verbose_name='数据质量问题'),
        ),
        migrations.AddField(
            model_name='contract',
            name='quality_score',
            field=models.PositiveIntegerField(default=100, verbose_name='数据质量评分'),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_contract_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='续签合同编号'),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_contracts', to=settings.AUTH_USER_MODEL, verbose_name='续签负责人'),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_reminder_days',
            field=models.PositiveIntegerField(default=30, verbose_name='续签提醒天数'),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_status',
            field=models.CharField(choices=[('none', '未设置'), ('pending', '待续签'), ('renewed', '已续签'), ('expired', '已到期'), ('not_renewed', '未续签')], default='none', max_length=20, verbose_name='续签状态'),
        ),
        migrations.AddField(
            model_name='contract',
            name='stamp_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='印花税金额'),
        ),
        migrations.AddField(
            model_name='contract',
            name='stamp_tax_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='印花税税率'),
        ),
        migrations.AddField(
            model_name='contract',
            name='terminated_at',
            field=models.DateField(blank=True, null=True, verbose_name='终止/作废时间'),
        ),
        migrations.AddField(
            model_name='contract',
            name='terminated_reason',
            field=models.TextField(blank=True, default='', verbose_name='终止/作废原因'),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_attachments',
            field=models.JSONField(blank=True, default=list, verbose_name='终止凭证'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='实付金额'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='invoice_status',
            field=models.CharField(choices=[('pending', '待开票'), ('issued', '已开票'), ('received', '已收票')], default='pending', max_length=20, verbose_name='发票状态'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='付款比例(%)'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='voucher_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='付款凭证号'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='status',
            field=models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('overdue', '逾期'), ('severe_overdue', '严重逾期')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_type', models.CharField(choices=[('delivery', '交付节点'), ('payment', '付款节点'), ('acceptance', '验收节点'), ('custom', '自定义节点')], max_length=20, verbose_name='节点类型')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('progress_weight', models.PositiveIntegerField(default=25, verbose_name='节点权重')),
                ('planned_date', models.DateField(verbose_name='计划完成时间')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际完成时间')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('overdue', '已逾期')], default='not_started', max_length=20, verbose_name='节点状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('evidences', models.JSONField(blank=True, default=list, verbose_name='凭证')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '合同履约节点',
                'verbose_name_plural': '合同履约节点',
                'db_table': 'biz_contract_milestone',
                'ordering': ['planned_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('core', '核心信息变更'), ('supplement', '补充协议')], default='core', max_length=20, verbose_name='变更类型')),
                ('title', models.CharField(max_length=200, verbose_name='变更标题')),
                ('reason', models.TextField(blank=True, default='', verbose_name='变更原因')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('before_snapshot', models.JSONField(blank=True, default=dict, verbose_name='变更前快照')),
                ('after_snapshot', models.JSONField(blank=True, default=dict, verbose_name='变更后快照')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='补充协议附件')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contract_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='contracts.contract', verbose_name='合同')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '合同变更申请',
                'verbose_name_plural': '合同变更申请',
                'db_table': 'biz_contract_change_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('create', '新增审批'), ('update', '修改审批'), ('delete', '删除审批'), ('change', '变更审批')], max_length=20, verbose_name='操作类型')),
                ('title', models.CharField(max_length=200, verbose_name='审批标题')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='审批数据')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态')),
                ('current_step', models.PositiveIntegerField(default=1, verbose_name='当前步骤')),
                ('review_logs', models.JSONField(blank=True, default=list, verbose_name='审批记录')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后审批时间')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='contracts.contract', verbose_name='合同')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='contracts.approvalprocess', verbose_name='审批流程')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='最后审批人')),
            ],
            options={
                'verbose_name': '审批申请',
                'verbose_name_plural': '审批申请',
                'db_table': 'biz_approval_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
